#spring settings
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: @jdbcUrl@
    username: @jdbcUsername@
    password: @jdbcPassword@
    hikari:
      connection-timeout: 2000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
  mail:
    host: @emailHost@
    port: @emailPort@
    username: @emailUsername@
    password: @emailPassword@
