#spring settings
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: @jdbc.url@
    username: @jdbc.username@
    password: @jdbc.password@
    hikari:
      connection-timeout: 2000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
  mail:
    host: @spring.mail.host@
    port: @spring.mail.port@
    username: @spring.mail.username@
    password:  @spring.mail.password@
