#spring settings
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/maxibetdb?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&stringtype=unspecified
    username: maxibet
    password: globalTLLC09
    hikari:
      connection-timeout: 2000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
  mail:
    host: smtp.qq.com
    port: 587
    username: yyds@qq.com 
    password:  yyds
